### ISSUE TITLE
PxSDK imageOriginal crashed app.

### ISSUE THREAD

**Issue by VinothKuppanna** [Pixelnetica/apple-ios-pdf-ocr-document-scanner#1]
After initial loaded image. When I try to rotate image and changed to black and white(PxSDK imageBWBinarization) then changed to normal mode(PxSDK imageOriginal) app crashed. Can anyone please tell me why this is happened ? how to fix this?

The crash log says
+[PxSDK imageBinarization:withMode:] + 284

@DmitryH 
@bigintnum

**Comment by iOSShiga** [comment]
app crashed when I opened camera in iOS 15. The crash is happened on CameraViewController file. Please find below the logs. Please help me to resolve the issue.


-[OverlayView clearView]: unrecognized selector sent to instance 0x10460a180

**Comment by DmitryH** [comment]
Check the latest update (v2.5.2). 
We fix iOS 15 compatibility.
