### ISSUE TITLE
Building for iOS, but the linked and embedded framework 'DocScanningSDK.framework' was built for iOS + iOS Simulator.

### ISSUE THREAD

**Issue by saiprabhu-bk** [Pixelnetica/apple-ios-pdf-ocr-document-scanner#3]
After Updating to Xcode 12.3, Not able to build the app
Error `Building for iOS, but the linked and embedded framework 'DocScanningSDK.framework' was built for iOS + iOS Simulator.`

**Comment by DmitryH** [comment]
Fixed in 2.5.1.   
Also make sure that `Validate Workspace` option set to `Yes` in `Build Options` (`Build Settings` tab).
